#!/bin/sh
set -e

case "$1" in
    configure)
        chmod ug+x /usr/local/bin/unbound-blacklist.py
        systemctl enable unbound-blacklist-updater.timer
        systemctl start unbound-blacklist-updater.timer
        systemctl start unbound-blacklist-updater.service
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
